# https://taskfile.dev

version: '3'

vars:
  VERSION:
    sh: dover

tasks:
  build:
    cmds:
      - rm -f bin/*
      - go build -o bin/pingu cli/*.go

  release:tag:
    cmds:
      - git tag -a v{{.VERSION}} -m "v{{.VERSION}}"

  release:build:
    cmds:
      - goreleaser build --snapshot --rm-dist

  release:
    cmds:
      - goreleaser release --rm-dist --skip-announce


  test:
    cmds:
      - gotestsum --format testname

  test:cover:
    cmds:
      - go test -coverprofile=cover.out ./...
      - go tool cover -html=cover.out
